import = [
    "~/.config/alacritty/theme.toml"
]

[env]
    TERM = "xterm-256color"

[font] 
    normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
    size = 13

[window]
    padding = {x = 8, y = 6}
    title = ""

[cursor]
    style = {shape = "Block", blinking="Always"}
    blink_interval = 500
